### ISSUE TITLE
Handle path lookup when distributing projects

### ISSUE THREAD

**Issue by matthewp** [matthewp/babel-plugin-modules-web-compat#2]
The needs of apps and libraries are different when it comes to package name resolution. For apps the path should point to the exact location of the file. For libraries that location is not going to be the same once distributed to users.

**Comment by matthewp** [comment]
@treshugart I'm thinking for this use case we just add an option instead of the more generic stuff we talked about.  Something like:

```json
{
  "plugins": [
    ["modules-web-compat", {
      "forDistribution": true
    }]
  ]
}
```

We can bikeshed on the option name, but I think this is easier than coming up with a DSL, since this is the only use-case for now.

**Comment by treshugart** [comment]
Maybe we should list the different scenarios. The one's I can think of are:

1. NPM
2. Manual
3. Bower
4. JSPM
5. ?

I think that 1 and 2 are the most common cases, but catering to NPM is probably the best place to start. Manual resolution is likely to be for apps, which can resolve to the exact location, like you said.

Would it be better to call the option `packageResolutionStrategy`? And have `"npm"` be the only option?

We can then think about making anything that doesn't match a valid option attempt to resolve a module with a default export that contains a function that returns a path to a module (resolving relative to the cwd or something).

I'm not attached yet to even providing that functionality, as we discussed in the meeting, but just spit-balling on some ideas. I think the main thing is getting NPM and exact resolution working.

With the NPM resolution, we need to keep in mind orgs, so we'll have to detect in both, the package that is doing the resolving, and the one being resolved and add a `../` for the one doing the resolving, and then the actual org in the one doing the resolving.

For example, if Resolving Preact from Skate in `src/`, we'd do something like `../../preact/src/index.js`. However, if both Skate and Preact created orgs and namespaced the packages, it would do something like `../../../@developit/preact/src/index.js`.

**Comment by matthewp** [comment]
I don't see why we need any special detection for orgs. It shouldn't matter, it's just adding an additional `../` when distributing.

If the structure is:

```js
app.js
node_modules/pkg/index.js
node_modules/org/pkg/index.js
```

Then app.js' imports should look like:

```js
import './node_modules/pkg/index.js';
import './node_modules/org/pkg/index.js';
```

And if using this new option it will look like:

```js
import '../node_modules/pkg/index.js';
import '../node_modules/org/pkg/index.js';
```

So we're just adding an extra `.`, that's really it!

Going to go with your suggestion of packageResolutionStrategy for now, even though I don't like it :) Will deprecate when we come up with something better, or allow users to have full control over resolution.

**Comment by treshugart** [comment]
> I don't see why we need any special detection for orgs. It shouldn't matter, it's just adding an additional ../ when distributing.

If you have an app - `my-app` - that depends on `@org-a/pkg-a`, and `@org-a/pkg-a` depends on `@org-b/pkg-b`, NPM will flatten the dependency tree unless `my-app` depends on a version of `@org-b/pkg-b` that is incompatible with the version spec that `@org-a/pkg-a` specifies.

For example, if they're compatible:

- my-app
  - node_modules
    - @org-a/pkg-a
    - @org-b/pkg-b

If they're not:

- my-app
  - node_modules
    - @org-a/pkg-a
      - node_modules/@org-b/pkg-b
    - @org-b/pkg-b

I did this with Skate 4.x and depended on an incompatible IncrementalDOM:

<img width="226" alt="screen shot 2017-05-23 at 12 31 36 pm" src="https://cloud.githubusercontent.com/assets/136556/26372776/d8aa2b70-3fb3-11e7-805c-bf02f7fb43c8.png">

And without specifying a dep on iDOM:

<img width="218" alt="screen shot 2017-05-23 at 12 37 42 pm" src="https://cloud.githubusercontent.com/assets/136556/26372979/aea7f86a-3fb4-11e7-9f6e-c48338c3c248.png">

In light of that, I'm not sure which one is best to follow. We should *always* get one from using the parent node modules (which means we have to detect org) but it just may be the wrong version.

**Comment by treshugart** [comment]
I realised I just did that with Yarn. Just to make sure, I did it again with NPM and it behaves the same.

**Comment by matthewp** [comment]
Just commenting that I haven't forgotten about this. Going to add org support to #4 before merging.

**Comment by matthewp** [comment]
@treshugart That problem is not fixable at build time, the user's dependencies will dictate where your dependencies are in the hierarchy. I think this is already become confusing enough so we need to assume a flat structure for now.
